In [1]:
import torch

In [10]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.4760, -1.6258,  1.6002], requires_grad=True)

In [11]:
y = x+2
y

tensor([2.4760, 0.3742, 3.6002], grad_fn=<AddBackward0>)

In [12]:
z = y*y*2
z

tensor([12.2613,  0.2800, 25.9225], grad_fn=<MulBackward0>)

In [13]:
z=z.mean()
z

tensor(12.8213, grad_fn=<MeanBackward0>)

In [14]:
z.backward() #dz/dx
x.grad

tensor([3.3013, 0.4989, 4.8002])

In [17]:
z2 = y*y*2
# z2.backward() #when z2 is not scalar, backward() will not work
#because in the background it is a vector jacobian product
#to make it working...
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z2.backward(v)
x.grad

tensor([5.2822, 3.4922, 4.8290])

In [18]:
#how to stop gradient tracking off
# 3 ways:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x.requires_grad_(False)
print(x)

tensor([ 0.4760, -1.6258,  1.6002])


In [19]:
x = torch.randn(3, requires_grad=True)
y = x.detach()
x, y

(tensor([ 1.0053, -0.1219, -2.4166], requires_grad=True),
 tensor([ 1.0053, -0.1219, -2.4166]))

In [21]:
with torch.no_grad():
  y = x+2
  print(y)
print(y), print(x)

tensor([ 3.0053,  1.8781, -0.4166])
tensor([ 3.0053,  1.8781, -0.4166])
tensor([ 1.0053, -0.1219, -2.4166], requires_grad=True)


(None, None)

In [23]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  #gradients are wrong

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [25]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr = 0.01)
optimizer.step()
optimizer.zero_grad() # will do the same as previous cell