In [24]:
import torch
import numpy as np

In [6]:
x = torch.empty(2,2,3)
x

tensor([[[5.1734e-14, 4.5087e-41, 5.1734e-14],
         [4.5087e-41, 4.4842e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 1.9361e+03],
         [3.1564e-41, 0.0000e+00, 0.0000e+00]]])

In [8]:
x = torch.rand(2,2, dtype = torch.float16) #torch.ones, torch.zeros
x, x.size(), x.dtype

(tensor([[0.7788, 0.0879],
         [0.7852, 0.4116]], dtype=torch.float16),
 torch.Size([2, 2]),
 torch.float16)

In [9]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [10]:
x =torch.rand(2,2)
y =torch.rand(2,2)
x, y

(tensor([[0.6616, 0.2072],
         [0.0065, 0.4339]]),
 tensor([[0.9689, 0.1859],
         [0.1835, 0.0088]]))

In [11]:
x +  y, torch.add(x,y)

(tensor([[1.6306, 0.3931],
         [0.1900, 0.4427]]),
 tensor([[1.6306, 0.3931],
         [0.1900, 0.4427]]))

In [12]:
y.add_(x) # _ inplace operation

tensor([[1.6306, 0.3931],
        [0.1900, 0.4427]])

In [15]:
x -  y, torch.sub(x,y), x *  y, torch.mul(x,y), x /  y, torch.div(x,y)

(tensor([[-0.9689, -0.1859],
         [-0.1835, -0.0088]]),
 tensor([[-0.9689, -0.1859],
         [-0.1835, -0.0088]]),
 tensor([[1.0788, 0.0814],
         [0.0012, 0.1921]]),
 tensor([[1.0788, 0.0814],
         [0.0012, 0.1921]]),
 tensor([[0.4058, 0.5271],
         [0.0343, 0.9801]]),
 tensor([[0.4058, 0.5271],
         [0.0343, 0.9801]]))

In [21]:
x = torch.rand(5,3)
x, x[:,0], x[1,:], x[1,1], x[1,1].item()

(tensor([[0.8319, 0.1656, 0.8021],
         [0.2426, 0.8480, 0.0603],
         [0.2882, 0.9694, 0.8841],
         [0.7461, 0.3356, 0.5440],
         [0.3109, 0.5008, 0.3247]]),
 tensor([0.8319, 0.2426, 0.2882, 0.7461, 0.3109]),
 tensor([0.2426, 0.8480, 0.0603]),
 tensor(0.8480),
 0.8479803800582886)

In [23]:
x =torch.rand(4,4)
x, x.view(16), x.view(-1,8)

(tensor([[0.7015, 0.2266, 0.2949, 0.4812],
         [0.8869, 0.6507, 0.9752, 0.1123],
         [0.2004, 0.3641, 0.8345, 0.1613],
         [0.3637, 0.2950, 0.1418, 0.0083]]),
 tensor([0.7015, 0.2266, 0.2949, 0.4812, 0.8869, 0.6507, 0.9752, 0.1123, 0.2004,
         0.3641, 0.8345, 0.1613, 0.3637, 0.2950, 0.1418, 0.0083]),
 tensor([[0.7015, 0.2266, 0.2949, 0.4812, 0.8869, 0.6507, 0.9752, 0.1123],
         [0.2004, 0.3641, 0.8345, 0.1613, 0.3637, 0.2950, 0.1418, 0.0083]]))

In [27]:
x = torch.ones(5)
y = x.numpy()
type(x), type(y)

(torch.Tensor, numpy.ndarray)

In [29]:
# if the tensor or numpy in cpu memory, they share same location
# in-place modification will affect the other one
x.add_(1)
x, y

(tensor([3., 3., 3., 3., 3.]), array([3., 3., 3., 3., 3.], dtype=float32))

In [31]:
x = np.ones(5)
y = torch.from_numpy(x)
x, y

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [34]:
x+=1
x, y

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [35]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y
  z = z.to("cpu")

In [36]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)