In [2]:
import torch

In [31]:
x = torch.randn(3, requires_grad=True)
x

tensor([0.4259, 0.0576, 0.6759], requires_grad=True)

In [32]:
y = x+2
y

tensor([2.4259, 2.0576, 2.6759], grad_fn=<AddBackward0>)

In [33]:
z = y*y*2
z

tensor([11.7698,  8.4675, 14.3208], grad_fn=<MulBackward0>)

In [34]:
z=z.mean()
z

tensor(11.5194, grad_fn=<MeanBackward0>)

In [35]:
z.backward() #dz/dx
x, x.grad

(tensor([0.4259, 0.0576, 0.6759], requires_grad=True),
 tensor([3.2345, 2.7435, 3.5679]))

In [36]:
z2 = y*y*2
# z2.backward() #when z2 is not scalar, backward() will not work
#because in the background it is a vector jacobian product
#to make it working...have to pass vector argument to the backward()

v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z2.backward(v)
x, x.grad

(tensor([0.4259, 0.0576, 0.6759], requires_grad=True),
 tensor([ 4.2049, 10.9739,  3.5786]))

In [ ]:
#how to stop gradient tracking off
# 3 ways:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x.requires_grad_(False)
print(x)

tensor([ 0.4760, -1.6258,  1.6002])


In [ ]:
x = torch.randn(3, requires_grad=True)
y = x.detach()
x, y

(tensor([ 1.0053, -0.1219, -2.4166], requires_grad=True),
 tensor([ 1.0053, -0.1219, -2.4166]))

In [ ]:
with torch.no_grad():
  y = x+2
  print(y)
print(y), print(x)

tensor([ 3.0053,  1.8781, -0.4166])
tensor([ 3.0053,  1.8781, -0.4166])
tensor([ 1.0053, -0.1219, -2.4166], requires_grad=True)


(None, None)

In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  #gradients are wrong

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr = 0.01)
optimizer.step()
optimizer.zero_grad() # will do the same as previous cell